Finished landing distance requirement, removed asteroids from planet …
j-rodriguez99/Infinite_Adventure pull request #27
Opened 2022-11-30 18:16 UTC by Mokimbo

…group. You start just outside of the planet landing range which I think is good. Updated the speed print so that you know what numbers are referring to in the godot console. Asteroids removed from the group since this group is just for planets and we figured out how to target things more efficiently already.

2022-11-30 18:32 UTC, alarner requested changes
The logic looks great! My only comment is on the speed and distance values. I think we should be slightly more strict.

2022-11-30 18:32 UTC, alarner commented on scenes/Ships/Ship_controls.gd
> +		if distance_check > 500:
I think we should require that they get closer. A value of 150 here I think would be good.

2022-11-30 18:32 UTC, alarner commented on scenes/Ships/Ship_controls.gd
>  	if speed_check > 250:
I think we should require that they are moving slower. A value of `50` here I think would be good.

2022-12-01 16:59 UTC, Mokimbo commented
changed the values so you need to be closer/ move slower

2022-12-01 22:51 UTC, alarner approved these changes

2022-12-01 23:35 UTC, merged